-- One-off pre-launch clearing script. Run deliberately, once, by a person.
-- NEVER referenced or executed by the migration chain (AGENTS.md, Database).
--
-- History: these two statements originally lived inside migrations
-- 20260831221014_fuzzy_korg (calculation_runs) and
-- 20260904060558_large_scalphunter (transaction_legs). Max revoked the
-- in-migration exception on 2026-09-05; the statements were moved here.
-- Both tables are derived state: calculation_runs is regenerated by recompute,
-- transaction_legs by source replay through the normal writers.
--
-- A database that already applied those migrations needs nothing from this file.
-- A fresh database runs the chain against empty tables and needs nothing either.

DELETE FROM "calculation_runs";
DELETE FROM "transaction_legs";
