import type {
  Account,
  AssetHolding,
  DashboardTransaction,
  TaxYear,
  TaxYearAccountSummary,
} from "./types"

export const taxYears: ReadonlyArray<TaxYear> = [2025, 2024, 2023]

const stressAccountNetworks = ["Ethereum", "Solana", "Base", "Arbitrum", "Optimism"] as const

const stressAccounts: ReadonlyArray<Account> = Array.from({ length: 23 }, (_, index) => {
  const displayIndex = index + 1
  const kind: Account["kind"] = index % 4 === 0 ? "exchange" : "wallet"
  const account = {
    id: `stress-account-${displayIndex.toString().padStart(2, "0")}`,
    name: kind === "exchange" ? `Exchange ${displayIndex}` : `Wallet ${displayIndex}`,
    kind,
    importedTransactions: 24 + displayIndex * 11,
    unresolvedItems: displayIndex % 5,
    lastSync: displayIndex % 2 === 0 ? "Today, 11:02" : "Yesterday, 17:45",
  }

  return kind === "wallet"
    ? { ...account, network: stressAccountNetworks[index % stressAccountNetworks.length] }
    : account
})

const stressTaxYearAccountSummaries: ReadonlyArray<TaxYearAccountSummary> = stressAccounts.flatMap(
  (account, accountIndex) =>
    taxYears.map((taxYear, yearIndex) => {
      const sign = (accountIndex + yearIndex) % 4 === 0 ? -1 : 1
      const realizedProfitLoss = sign * (82 + accountIndex * 19 + yearIndex * 44)

      return {
        accountId: account.id,
        taxYear,
        realizedProfitLoss,
        taxesPayable: realizedProfitLoss > 0 ? realizedProfitLoss * 0.42 : 0,
        taxesReceivable: realizedProfitLoss < 0 ? Math.abs(realizedProfitLoss) * 0.26 : 0,
        taxableEvents: 4 + accountIndex + yearIndex * 3,
        missingClassifications: taxYear === 2025 ? account.unresolvedItems : 0,
      }
    })
)

const stressAssetLots = stressAccounts.map((account, index) => ({
  accountId: account.id,
  amount: 10 + index * 2.4,
  value: 640 + index * 178,
  costBasis: 560 + index * 153,
}))

const accountFixtures: ReadonlyArray<Account> = [
  {
    id: "coinbase",
    name: "Coinbase",
    kind: "exchange",
    importedTransactions: 418,
    unresolvedItems: 2,
    lastSync: "Today, 09:41",
  },
  {
    id: "kraken",
    name: "Kraken",
    kind: "exchange",
    importedTransactions: 126,
    unresolvedItems: 0,
    lastSync: "Yesterday, 18:22",
  },
  {
    id: "solana-wallet",
    name: "Solana wallet",
    kind: "wallet",
    network: "Solana",
    importedTransactions: 87,
    unresolvedItems: 4,
    lastSync: "Today, 08:13",
  },
  {
    id: "binance",
    name: "Binance",
    kind: "exchange",
    importedTransactions: 302,
    unresolvedItems: 1,
    lastSync: "Today, 07:58",
  },
  {
    id: "ledger",
    name: "Ledger vault",
    kind: "wallet",
    network: "Ethereum",
    importedTransactions: 41,
    unresolvedItems: 0,
    lastSync: "Mon, 16:08",
  },
  {
    id: "metamask",
    name: "MetaMask",
    kind: "wallet",
    network: "Ethereum",
    importedTransactions: 156,
    unresolvedItems: 3,
    lastSync: "Today, 10:12",
  },
  {
    id: "base-wallet",
    name: "Base wallet",
    kind: "wallet",
    network: "Base",
    importedTransactions: 64,
    unresolvedItems: 2,
    lastSync: "Yesterday, 21:34",
  },
  {
    id: "arbitrum-wallet",
    name: "Arbitrum",
    kind: "wallet",
    network: "Arbitrum",
    importedTransactions: 93,
    unresolvedItems: 1,
    lastSync: "Today, 06:25",
  },
  ...stressAccounts,
]

export const accounts: ReadonlyArray<Account> = accountFixtures.slice(0, 8)

export const taxYearAccountSummaries: ReadonlyArray<TaxYearAccountSummary> = [
  {
    accountId: "coinbase",
    taxYear: 2025,
    realizedProfitLoss: 2841.12,
    taxesPayable: 1193.27,
    taxesReceivable: 0,
    taxableEvents: 73,
    missingClassifications: 1,
  },
  {
    accountId: "kraken",
    taxYear: 2025,
    realizedProfitLoss: -318.44,
    taxesPayable: 0,
    taxesReceivable: 84.12,
    taxableEvents: 19,
    missingClassifications: 0,
  },
  {
    accountId: "solana-wallet",
    taxYear: 2025,
    realizedProfitLoss: 214.2,
    taxesPayable: 89.96,
    taxesReceivable: 0,
    taxableEvents: 6,
    missingClassifications: 4,
  },
  {
    accountId: "binance",
    taxYear: 2025,
    realizedProfitLoss: 1204.88,
    taxesPayable: 505.04,
    taxesReceivable: 0,
    taxableEvents: 51,
    missingClassifications: 1,
  },
  {
    accountId: "ledger",
    taxYear: 2025,
    realizedProfitLoss: 0,
    taxesPayable: 0,
    taxesReceivable: 0,
    taxableEvents: 2,
    missingClassifications: 0,
  },
  {
    accountId: "metamask",
    taxYear: 2025,
    realizedProfitLoss: -141.76,
    taxesPayable: 0,
    taxesReceivable: 37.55,
    taxableEvents: 28,
    missingClassifications: 3,
  },
  {
    accountId: "base-wallet",
    taxYear: 2025,
    realizedProfitLoss: 82.44,
    taxesPayable: 34.62,
    taxesReceivable: 0,
    taxableEvents: 12,
    missingClassifications: 2,
  },
  {
    accountId: "arbitrum-wallet",
    taxYear: 2025,
    realizedProfitLoss: 318.12,
    taxesPayable: 133.61,
    taxesReceivable: 0,
    taxableEvents: 17,
    missingClassifications: 1,
  },
  {
    accountId: "coinbase",
    taxYear: 2024,
    realizedProfitLoss: 1486.9,
    taxesPayable: 624.5,
    taxesReceivable: 0,
    taxableEvents: 44,
    missingClassifications: 0,
  },
  {
    accountId: "kraken",
    taxYear: 2024,
    realizedProfitLoss: 711.4,
    taxesPayable: 298.78,
    taxesReceivable: 0,
    taxableEvents: 16,
    missingClassifications: 0,
  },
  {
    accountId: "solana-wallet",
    taxYear: 2024,
    realizedProfitLoss: -82.32,
    taxesPayable: 0,
    taxesReceivable: 21.8,
    taxableEvents: 5,
    missingClassifications: 1,
  },
  {
    accountId: "binance",
    taxYear: 2024,
    realizedProfitLoss: 942.18,
    taxesPayable: 395.72,
    taxesReceivable: 0,
    taxableEvents: 39,
    missingClassifications: 0,
  },
  {
    accountId: "ledger",
    taxYear: 2024,
    realizedProfitLoss: 0,
    taxesPayable: 0,
    taxesReceivable: 0,
    taxableEvents: 0,
    missingClassifications: 0,
  },
  {
    accountId: "metamask",
    taxYear: 2024,
    realizedProfitLoss: 264.48,
    taxesPayable: 111.08,
    taxesReceivable: 0,
    taxableEvents: 21,
    missingClassifications: 0,
  },
  {
    accountId: "base-wallet",
    taxYear: 2024,
    realizedProfitLoss: -38.1,
    taxesPayable: 0,
    taxesReceivable: 10.1,
    taxableEvents: 8,
    missingClassifications: 0,
  },
  {
    accountId: "arbitrum-wallet",
    taxYear: 2024,
    realizedProfitLoss: 126.2,
    taxesPayable: 53,
    taxesReceivable: 0,
    taxableEvents: 12,
    missingClassifications: 0,
  },
  {
    accountId: "coinbase",
    taxYear: 2023,
    realizedProfitLoss: -902.44,
    taxesPayable: 0,
    taxesReceivable: 238.9,
    taxableEvents: 38,
    missingClassifications: 0,
  },
  {
    accountId: "kraken",
    taxYear: 2023,
    realizedProfitLoss: 142.18,
    taxesPayable: 59.72,
    taxesReceivable: 0,
    taxableEvents: 9,
    missingClassifications: 0,
  },
  {
    accountId: "solana-wallet",
    taxYear: 2023,
    realizedProfitLoss: 0,
    taxesPayable: 0,
    taxesReceivable: 0,
    taxableEvents: 0,
    missingClassifications: 0,
  },
  {
    accountId: "binance",
    taxYear: 2023,
    realizedProfitLoss: 312.44,
    taxesPayable: 131.22,
    taxesReceivable: 0,
    taxableEvents: 18,
    missingClassifications: 0,
  },
  {
    accountId: "ledger",
    taxYear: 2023,
    realizedProfitLoss: 0,
    taxesPayable: 0,
    taxesReceivable: 0,
    taxableEvents: 0,
    missingClassifications: 0,
  },
  {
    accountId: "metamask",
    taxYear: 2023,
    realizedProfitLoss: -76.8,
    taxesPayable: 0,
    taxesReceivable: 20.35,
    taxableEvents: 9,
    missingClassifications: 0,
  },
  {
    accountId: "base-wallet",
    taxYear: 2023,
    realizedProfitLoss: 0,
    taxesPayable: 0,
    taxesReceivable: 0,
    taxableEvents: 0,
    missingClassifications: 0,
  },
  {
    accountId: "arbitrum-wallet",
    taxYear: 2023,
    realizedProfitLoss: 44.2,
    taxesPayable: 18.56,
    taxesReceivable: 0,
    taxableEvents: 4,
    missingClassifications: 0,
  },
  ...stressTaxYearAccountSummaries,
]

export const assetHoldings: ReadonlyArray<AssetHolding> = [
  {
    asset: "BTC",
    name: "Bitcoin",
    lots: [
      { accountId: "coinbase", amount: 0.1242, value: 7031.82, costBasis: 5024.2 },
      { accountId: "binance", amount: 0.084, value: 4757.59, costBasis: 4120.2 },
      { accountId: "ledger", amount: 0.21, value: 11893.98, costBasis: 9980 },
      { accountId: "solana-wallet", amount: 0.06, value: 3398.28, costBasis: 3060.11 },
    ],
  },
  {
    asset: "ETH",
    name: "Ethereum",
    lots: [
      { accountId: "coinbase", amount: 1.32, value: 4372.64, costBasis: 3811.88 },
      { accountId: "kraken", amount: 1.09, value: 3611.8, costBasis: 3440.92 },
      { accountId: "metamask", amount: 0.74, value: 2451.12, costBasis: 2694.33 },
      { accountId: "arbitrum-wallet", amount: 0.38, value: 1258.68, costBasis: 1042.5 },
    ],
  },
  {
    asset: "SOL",
    name: "Solana",
    lots: [{ accountId: "solana-wallet", amount: 96.5, value: 15826.72, costBasis: 12114.4 }],
  },
  {
    asset: "USDC",
    name: "USD Coin",
    lots: [
      { accountId: "coinbase", amount: 1204.22, value: 1204.22, costBasis: 1204.22 },
      { accountId: "base-wallet", amount: 842.44, value: 842.44, costBasis: 842.44 },
    ],
  },
  {
    asset: "LINK",
    name: "Chainlink",
    lots: [
      { accountId: "kraken", amount: 84.4, value: 1492.9, costBasis: 1880.1 },
      { accountId: "binance", amount: 42.2, value: 746.45, costBasis: 691.3 },
    ],
  },
  {
    asset: "ARB",
    name: "Arbitrum",
    lots: [{ accountId: "arbitrum-wallet", amount: 1842, value: 1547.28, costBasis: 1336.5 }],
  },
  {
    asset: "AERO",
    name: "Aerodrome",
    lots: [{ accountId: "base-wallet", amount: 620, value: 781.2, costBasis: 698.76 }],
  },
  {
    asset: "TEST",
    name: "Stress Test Token",
    lots: stressAssetLots,
  },
]

export const transactions: ReadonlyArray<DashboardTransaction> = [
  {
    id: "tx-001",
    accountId: "coinbase",
    taxYear: 2025,
    date: "2025-04-12",
    asset: "BTC",
    rawAction: "Sell",
    taxTreatment: "Taxable disposal",
    amount: -0.032,
    value: 9280,
    realizedProfitLoss: 1724.31,
    taxImpact: 724.21,
    txId: "CB-81F7",
    taxRelevant: true,
  },
  {
    id: "tx-002",
    accountId: "coinbase",
    taxYear: 2025,
    date: "2025-03-03",
    asset: "ETH",
    rawAction: "Sell",
    taxTreatment: "Taxable disposal",
    amount: -1.1,
    value: 3660.5,
    realizedProfitLoss: 986.42,
    taxImpact: 414.3,
    txId: "CB-7AC2",
    taxRelevant: true,
  },
  {
    id: "tx-003",
    accountId: "kraken",
    taxYear: 2025,
    date: "2025-02-21",
    asset: "LINK",
    rawAction: "Sell",
    taxTreatment: "Taxable disposal",
    amount: -42,
    value: 731.22,
    realizedProfitLoss: -318.44,
    taxImpact: -84.12,
    txId: "KR-13B0",
    taxRelevant: true,
  },
  {
    id: "tx-004",
    accountId: "solana-wallet",
    taxYear: 2025,
    date: "2025-02-09",
    asset: "SOL",
    rawAction: "Swap",
    taxTreatment: "Taxable disposal",
    amount: -18.5,
    value: 3104.9,
    realizedProfitLoss: 130.39,
    taxImpact: 54.76,
    txId: "5nQ9...V3kF",
    taxRelevant: true,
  },
  {
    id: "tx-005",
    accountId: "solana-wallet",
    taxYear: 2025,
    date: "2025-01-18",
    asset: "USDC",
    rawAction: "Transfer in",
    taxTreatment: "Matched transfer",
    amount: 1204.22,
    value: 1204.22,
    realizedProfitLoss: 0,
    taxImpact: 0,
    txId: "8Ae3...mK2p",
    taxRelevant: false,
  },
  {
    id: "tx-006",
    accountId: "coinbase",
    taxYear: 2024,
    date: "2024-11-27",
    asset: "ETH",
    rawAction: "Sell",
    taxTreatment: "Taxable disposal",
    amount: -0.8,
    value: 2490.1,
    realizedProfitLoss: 812.34,
    taxImpact: 341.18,
    txId: "CB-62DD",
    taxRelevant: true,
  },
  {
    id: "tx-007",
    accountId: "kraken",
    taxYear: 2024,
    date: "2024-08-06",
    asset: "BTC",
    rawAction: "Buy",
    taxTreatment: "Acquisition",
    amount: 0.044,
    value: 2418.8,
    realizedProfitLoss: 0,
    taxImpact: 0,
    txId: "KR-9021",
    taxRelevant: false,
  },
  {
    id: "tx-008",
    accountId: "coinbase",
    taxYear: 2023,
    date: "2023-10-10",
    asset: "BTC",
    rawAction: "Sell",
    taxTreatment: "Taxable disposal",
    amount: -0.028,
    value: 830.14,
    realizedProfitLoss: -902.44,
    taxImpact: -238.9,
    txId: "CB-44E1",
    taxRelevant: true,
  },
]
