import { createFileRoute, Link } from "@tanstack/react-router"
import { useId } from "react"

import { LegalPageShell } from "#/components/legal-page-shell"
import { LegalSectionCard } from "#/components/legal-section-card"

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      {
        name: "robots",
        content: "noindex",
      },
    ],
  }),
  component: TermsComponent,
})

function TermsComponent() {
  const ids = {
    intro: useId(),
    scope: useId(),
    eligibility: useId(),
    accounts: useId(),
    userDuties: useId(),
    taxDisclaimer: useId(),
    thirdParties: useId(),
    fees: useId(),
    ip: useId(),
    prohibited: useId(),
    liability: useId(),
    indemnity: useId(),
    termination: useId(),
    governingLaw: useId(),
    changes: useId(),
    contact: useId(),
  }

  const tableOfContents = [
    { href: `#${ids.scope}`, label: "Scope of Services" },
    { href: `#${ids.eligibility}`, label: "Eligibility" },
    { href: `#${ids.accounts}`, label: "Accounts and Security" },
    { href: `#${ids.userDuties}`, label: "User Responsibilities" },
    { href: `#${ids.taxDisclaimer}`, label: "No Tax Advice and Liability Disclaimer" },
    { href: `#${ids.thirdParties}`, label: "Third-Party Services and Data Sources" },
    { href: `#${ids.fees}`, label: "Fees and Payment" },
    { href: `#${ids.ip}`, label: "Intellectual Property" },
    { href: `#${ids.prohibited}`, label: "Prohibited Uses" },
    { href: `#${ids.liability}`, label: "Limitation of Liability" },
    { href: `#${ids.indemnity}`, label: "Indemnification" },
    { href: `#${ids.termination}`, label: "Suspension and Termination" },
    { href: `#${ids.governingLaw}`, label: "Governing Law and Jurisdiction" },
    { href: `#${ids.changes}`, label: "Changes to these Terms" },
    { href: `#${ids.contact}`, label: "Contact" },
  ] as const

  return (
    <LegalPageShell
      description="Welcome to TaxMaxi, a crypto tax reporting SaaS. By using our services, you agree to these Terms and Conditions."
      tableOfContents={tableOfContents}
      title="Terms and Conditions"
    >
      <LegalSectionCard id={ids.scope} title="1. Scope of Services">
        <p>
          TaxMaxi provides software to assist users in aggregating blockchain transaction data,
          categorizing transactions, calculating tax-relevant figures, and generating tax reports.
          TaxMaxi is not a certified tax advisor or law firm and does not provide legal or tax
          advice.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.eligibility} title="2. Eligibility">
        <p>You must be at least 18 years old to use TaxMaxi.</p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.accounts} title="3. Accounts and Security">
        <ul>
          <li>Provide accurate, current, and complete information when creating an account.</li>
          <li>
            You are responsible for maintaining the confidentiality of your credentials and for all
            activities under your account.
          </li>
          <li>Notify us immediately of any unauthorized use of your account.</li>
        </ul>
      </LegalSectionCard>

      <LegalSectionCard id={ids.userDuties} title="4. User Responsibilities">
        <ul>
          <li>
            You are solely responsible for the accuracy and completeness of the data you provide to
            TaxMaxi.
          </li>
          <li>Do not upload or submit unlawful, defamatory, or infringing content.</li>
          <li>
            Respect the rights and privacy of others; do not engage in harassment, discrimination,
            or hate speech.
          </li>
        </ul>
      </LegalSectionCard>

      <LegalSectionCard id={ids.taxDisclaimer} title="5. No Tax Advice and Liability Disclaimer">
        <p>
          TaxMaxi is not a certified tax advisor (Steuerberater) and does not provide tax, legal, or
          financial advice. Outputs generated by the service, including categorizations,
          calculations, and reports, are for informational purposes only and are not a substitute
          for professional advice tailored to your specific circumstances.
        </p>
        <p>
          You are solely responsible for reviewing, validating, and ensuring the correctness of all
          data and results before submitting any information to tax authorities. TaxMaxi assumes no
          liability for the accuracy, completeness, or fitness for a particular purpose of any
          generated report or calculation.
        </p>
        <p>
          Without limiting the foregoing, TaxMaxi assumes no liability for outcomes of audits,
          assessments, penalties, interest, or other measures by tax authorities, nor for
          consequences arising from errors in the data you provide or third‑party data sources.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.thirdParties} title="6. Third-Party Services and Data Sources">
        <p>
          TaxMaxi may integrate with third‑party services (e.g., Alchemy, Etherscan, CoinGecko) to
          fetch blockchain and pricing data. Availability, accuracy, and latency depend on those
          providers, and we are not responsible for their services. You authorize TaxMaxi to
          transmit data necessary to retrieve your information from such providers.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.fees} title="7. Fees and Payment">
        <p>
          Fees, if applicable, will be displayed at the time of purchase. All fees are
          non‑refundable unless required by law.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.ip} title="8. Intellectual Property">
        <p>
          The service, including all software, documentation, and content, is protected by
          intellectual property laws. Except as expressly permitted, you may not copy, modify,
          distribute, or create derivative works of the service.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.prohibited} title="9. Prohibited Uses">
        <ul>
          <li>No unlawful, fraudulent, or malicious activities.</li>
          <li>No reverse engineering, decompiling, or circumventing security or rate limits.</li>
          <li>No unauthorized access to other users’ data or our systems.</li>
        </ul>
      </LegalSectionCard>

      <LegalSectionCard id={ids.liability} title="10. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, TaxMaxi and its affiliates shall not be liable for
          any indirect, incidental, special, consequential, punitive, or exemplary damages, or for
          lost profits, lost revenues, loss of data, or downtime, even if advised of the possibility
          of such damages.
        </p>
        <p>
          In no event shall our aggregate liability exceed the amount you paid for the service
          during the twelve (12) months preceding the claim.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.indemnity} title="11. Indemnification">
        <p>
          You agree to indemnify and hold harmless TaxMaxi, its affiliates, and their officers,
          directors, and employees from any claims, damages, liabilities, and expenses arising from
          your use of the service, your breach of these Terms, or your violation of any law or
          third‑party rights.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.termination} title="12. Suspension and Termination">
        <p>
          We may suspend or terminate access to the service at any time, with or without notice,
          including for suspected violations of these Terms or to protect the integrity of the
          service.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.governingLaw} title="13. Governing Law and Jurisdiction">
        <p>
          These Terms are governed by the laws of the Federal Republic of Germany. The exclusive
          place of jurisdiction is Berlin, Germany.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.changes} title="14. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be notified within the
          service. Your continued use after changes become effective constitutes acceptance of the
          updated Terms.
        </p>
      </LegalSectionCard>

      <LegalSectionCard id={ids.contact} title="15. Contact">
        <div className="space-y-3">
          <p>
            <strong>TaxMaxi UG (haftungsbeschränkt)</strong>
          </p>
          <address>
            Belforter Str. 9
            <br />
            10405 Berlin, Germany
          </address>
          <p>
            <a href="mailto:team@taxmaxi.com">team@taxmaxi.com</a>
          </p>
          <p>
            Please also review our <Link to="/privacy">Privacy Notice</Link>.
          </p>
        </div>
      </LegalSectionCard>
    </LegalPageShell>
  )
}
