/**
 * SessionRepository - Repository interface for Session entity persistence
 *
 * Uses Effect Context.Tag pattern for dependency injection.
 * All operations return Effect with typed errors.
 *
 * @module SessionRepository
 */

import type * as Chunk from "effect/Chunk"
import * as Context from "effect/Context"
import type * as Effect from "effect/Effect"
import type * as Option from "effect/Option"
import type {
  AuthProviderType,
  AuthUserId,
  SessionId,
  Session,
  UserAgent,
} from "@my/core/authentication"
import type { Timestamp } from "@my/core/shared/values/Timestamp"
import type { EntityNotFoundError, PersistenceError } from "../errors/RepositoryError.ts"

/**
 * SessionInsert - Data required to create a new Session
 *
 * Contains all fields needed for session creation. The id is a secure random
 * token generated by the service layer (SessionTokenGenerator).
 */
export interface SessionInsert {
  readonly id: SessionId
  readonly userId: AuthUserId
  readonly provider: AuthProviderType
  readonly expiresAt: Timestamp
  readonly userAgent: Option.Option<UserAgent>
}

/**
 * SessionRepositoryService - Service interface for Session persistence
 *
 * Provides CRUD operations for Session entities with typed error handling.
 */
export interface SessionRepositoryService {
  /**
   * Find a session by its unique identifier
   *
   * @param id - The session ID to search for
   * @returns Effect containing Option of Session (None if not found)
   */
  readonly findById: (id: SessionId) => Effect.Effect<Option.Option<Session>, PersistenceError>

  /**
   * Find all sessions for a user
   *
   * @param userId - The user ID to search for
   * @returns Effect containing Chunk of Session
   */
  readonly findByUserId: (
    userId: AuthUserId
  ) => Effect.Effect<Chunk.Chunk<Session>, PersistenceError>

  /**
   * Create a new session
   *
   * @param session - The session data to create
   * @returns Effect containing the created Session
   */
  readonly create: (session: SessionInsert) => Effect.Effect<Session, PersistenceError>

  /**
   * Delete a session by its ID
   *
   * @param id - The session ID to delete
   * @returns Effect containing void on success
   */
  readonly delete: (id: SessionId) => Effect.Effect<void, PersistenceError>

  /**
   * Delete all expired sessions
   *
   * @returns Effect containing the number of deleted sessions
   */
  readonly deleteExpired: () => Effect.Effect<number, PersistenceError>

  /**
   * Delete all sessions for a user (logout from all devices)
   *
   * @param userId - The user ID whose sessions to delete
   * @returns Effect containing the number of deleted sessions
   */
  readonly deleteByUserId: (userId: AuthUserId) => Effect.Effect<number, PersistenceError>

  /**
   * Update the expiration time of a session (for session extension/refresh)
   *
   * @param id - The session ID to update
   * @param expiresAt - The new expiration timestamp
   * @returns Effect containing the updated Session
   * @throws EntityNotFoundError if session doesn't exist
   */
  readonly updateExpiry: (
    id: SessionId,
    expiresAt: Timestamp
  ) => Effect.Effect<Session, EntityNotFoundError | PersistenceError>
}

/**
 * SessionRepository - Context.Tag for dependency injection
 *
 * Usage:
 * ```typescript
 * import { SessionRepository } from "@my/persistence/services"
 *
 * const program = Effect.gen(function* () {
 *   const repo = yield* SessionRepository
 *   const session = yield* repo.findById(sessionId)
 *   // ...
 * })
 * ```
 */
export class SessionRepository extends Context.Tag("SessionRepository")<
  SessionRepository,
  SessionRepositoryService
>() {}
