/**
 * UserRepository - Repository interface for AuthUser entity persistence
 *
 * Uses Effect Context.Tag pattern for dependency injection.
 * All operations return Effect with typed errors.
 *
 * @module UserRepository
 */

import * as Context from "effect/Context"
import type * as Effect from "effect/Effect"
import type * as Option from "effect/Option"
import type {
  AuthUser,
  UserRole,
  AuthUserId,
  AuthProviderType,
  Email,
} from "@my/core/authentication"
import type { EntityNotFoundError, PersistenceError } from "../errors/RepositoryError.ts"

/**
 * AuthUserInsert - Data required to create a new AuthUser
 *
 * Contains all fields needed for user creation. The id, createdAt, and updatedAt
 * fields are provided by the caller (typically generated by the service layer).
 */
export interface AuthUserInsert {
  readonly id: AuthUserId
  readonly email: Email
  readonly displayName: string
  readonly role: UserRole
  readonly primaryProvider: AuthProviderType
  readonly emailVerified: boolean
}

/**
 * AuthUserUpdate - Data for updating an existing AuthUser
 *
 * All fields are optional - only provided fields will be updated.
 * The id and createdAt cannot be updated.
 */
export interface AuthUserUpdate {
  readonly email?: Email
  readonly displayName?: string
  readonly role?: UserRole
  readonly primaryProvider?: AuthProviderType
  readonly emailVerified?: boolean
}

/**
 * UserRepositoryService - Service interface for AuthUser persistence
 *
 * Provides CRUD operations for AuthUser entities with typed error handling.
 */
export interface UserRepositoryService {
  /**
   * Find a user by their unique identifier
   *
   * @param id - The user ID to search for
   * @returns Effect containing Option of AuthUser (None if not found)
   */
  readonly findById: (id: AuthUserId) => Effect.Effect<Option.Option<AuthUser>, PersistenceError>

  /**
   * Find a user by their email address
   *
   * @param email - The email address to search for
   * @returns Effect containing Option of AuthUser (None if not found)
   */
  readonly findByEmail: (email: Email) => Effect.Effect<Option.Option<AuthUser>, PersistenceError>

  /**
   * Create a new user
   *
   * @param user - The user data to create
   * @returns Effect containing the created AuthUser
   */
  readonly create: (user: AuthUserInsert) => Effect.Effect<AuthUser, PersistenceError>

  /**
   * Update an existing user
   *
   * @param id - The user ID to update
   * @param data - The fields to update
   * @returns Effect containing the updated AuthUser
   * @throws EntityNotFoundError if user doesn't exist
   */
  readonly update: (
    id: AuthUserId,
    data: AuthUserUpdate
  ) => Effect.Effect<AuthUser, EntityNotFoundError | PersistenceError>

  /**
   * Delete a user by their ID
   *
   * @param id - The user ID to delete
   * @returns Effect containing void on success
   * @throws EntityNotFoundError if user doesn't exist
   */
  readonly delete: (id: AuthUserId) => Effect.Effect<void, EntityNotFoundError | PersistenceError>

  /**
   * Find all platform administrators
   *
   * @returns Effect containing array of platform admin users
   */
  readonly findPlatformAdmins: () => Effect.Effect<readonly AuthUser[], PersistenceError>

  /**
   * Check if a user is a platform administrator
   *
   * @param id - The user ID to check
   * @returns Effect containing true if the user is a platform admin, false otherwise
   */
  readonly isPlatformAdmin: (id: AuthUserId) => Effect.Effect<boolean, PersistenceError>
}

/**
 * UserRepository - Context.Tag for dependency injection
 *
 * Usage:
 * ```typescript
 * import { UserRepository } from "@my/persistence/services"
 *
 * const program = Effect.gen(function* () {
 *   const repo = yield* UserRepository
 *   const user = yield* repo.findById(userId)
 *   // ...
 * })
 * ```
 */
export class UserRepository extends Context.Tag("UserRepository")<
  UserRepository,
  UserRepositoryService
>() {}
