/**
 * Default durable Coinbase transaction-type and currency mappings.
 *
 * @module CoinbaseDefaultReferenceMappings
 */

import type {
  ProviderAssetMappingKind,
  ProviderAssetMappingStatus,
} from "../../../services/ProviderAssetRepository.ts"
import type {
  ProviderInventoryEffect,
  ProviderMappingStatus,
  ProviderResolutionStrategy,
  ProviderTaxTreatment,
} from "../../../services/ProviderReferenceRepository.ts"

export interface CoinbaseDefaultTransactionTypeMapping {
  readonly providerTransactionType: string
  readonly transactionTypeKey: string | null
  readonly inventoryEffect: ProviderInventoryEffect
  readonly taxTreatment: ProviderTaxTreatment
  readonly resolutionStrategy: ProviderResolutionStrategy
  readonly pairedRecordRequired: boolean
  readonly mappingStatus: ProviderMappingStatus
  readonly sourceNotes: string
}

export interface CoinbaseDefaultCurrencyMapping {
  readonly currencyCode: string
  readonly mappingKind: ProviderAssetMappingKind
  readonly canonicalAssetSymbol: string | null
  readonly canonicalFiatCurrency: string | null
  readonly mappingStatus: ProviderAssetMappingStatus
  readonly sourceNotes: string
}

export const coinbaseDefaultTransactionTypeMappings: ReadonlyArray<CoinbaseDefaultTransactionTypeMapping> =
  [
    {
      providerTransactionType: "advanced_trade_fill",
      transactionTypeKey: "trade_other",
      inventoryEffect: "unknown",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "venue_side",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Advanced Trade fills resolve to acquisition/disposal from venue side.",
    },
    {
      providerTransactionType: "buy",
      transactionTypeKey: "buy_fiat",
      inventoryEffect: "acquisition",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Coinbase buy is a direct acquisition.",
    },
    {
      providerTransactionType: "clawback",
      transactionTypeKey: "chargeback",
      inventoryEffect: "non_inventory",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Clawbacks reverse prior provider-side disbursements.",
    },
    {
      providerTransactionType: "derivatives_settlement",
      transactionTypeKey: "derivative_profit_received",
      inventoryEffect: "non_inventory",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Settlement cash movements stay out of spot inventory normalization for now.",
    },
    {
      providerTransactionType: "earn_payout",
      transactionTypeKey: "staking_reward",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Coinbase earn payouts are treated as taxable reward income.",
    },
    {
      providerTransactionType: "interest",
      transactionTypeKey: "interest_received",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Coinbase interest rows are treated as interest income.",
    },
    {
      providerTransactionType: "fiat_deposit",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "non_inventory",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Fiat account funding is cataloged but excluded from crypto inventory legs.",
    },
    {
      providerTransactionType: "fiat_withdrawal",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "non_inventory",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Fiat withdrawals are cataloged but excluded from crypto inventory legs.",
    },
    {
      providerTransactionType: "incentives_rewards_payout",
      transactionTypeKey: "other_income",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Incentive payouts are taxable income by default.",
    },
    {
      providerTransactionType: "incentives_shared_clawback",
      transactionTypeKey: "chargeback",
      inventoryEffect: "non_inventory",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Shared clawbacks reverse prior incentive payouts.",
    },
    {
      providerTransactionType: "intx_deposit",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "amount_sign",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "International account transfers preserve inventory ownership.",
    },
    {
      providerTransactionType: "intx_withdrawal",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "amount_sign",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "International account transfers preserve inventory ownership.",
    },
    {
      providerTransactionType: "receive",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "acquisition",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "amount_sign",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Receives create inventory but may still need review for gifts/payments.",
    },
    {
      providerTransactionType: "request",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "unknown",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Requests are cataloged but not leg-derived without a completed movement.",
    },
    {
      providerTransactionType: "retail_simple_dust",
      transactionTypeKey: "fee",
      inventoryEffect: "non_inventory",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Dust sweeps are preserved for audit but excluded from deterministic legs.",
    },
    {
      providerTransactionType: "retail_simple_price_improvement",
      transactionTypeKey: "cashback",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes:
        "Coinbase simple-trade price improvement is treated as a rebate-like income credit.",
    },
    {
      providerTransactionType: "sell",
      transactionTypeKey: "sell_fiat",
      inventoryEffect: "disposal",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Coinbase sell is a direct disposal.",
    },
    {
      providerTransactionType: "send",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "unknown",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes:
        "Sends are preserved for review but excluded from deterministic tax legs until the user confirms self-transfer, gift, or payment treatment.",
    },
    {
      providerTransactionType: "staking_transfer",
      transactionTypeKey: "staking_deposit",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Staking deposits move inventory into a staking bucket without disposal.",
    },
    {
      providerTransactionType: "subscription_rebate",
      transactionTypeKey: "cashback",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Subscription rebates are treated as provider-side income.",
    },
    {
      providerTransactionType: "subscription",
      transactionTypeKey: "platform_fee",
      inventoryEffect: "non_inventory",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Subscription fees are cataloged but not converted into inventory legs.",
    },
    {
      providerTransactionType: "trade",
      transactionTypeKey: "swap_crypto_to_crypto",
      inventoryEffect: "unknown",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "amount_sign",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes: "Trade rows are sign-driven and may come in paired provider records.",
    },
    {
      providerTransactionType: "transfer",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "amount_sign",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes: "Provider transfers are sign-driven internal movements.",
    },
    {
      providerTransactionType: "tx",
      transactionTypeKey: "uncategorized",
      inventoryEffect: "unknown",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Default Coinbase catch-all remains uncategorized until reviewed.",
    },
    {
      providerTransactionType: "unstaking_transfer",
      transactionTypeKey: "staking_withdrawal",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Standard unstaking transfers restore principal without a taxable disposal.",
    },
    {
      providerTransactionType: "unsupported_asset_recovery",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Unsupported asset recovery is treated as a custody movement.",
    },
    {
      providerTransactionType: "unwrap_asset",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes: "Wrap/unwrap actions are modeled as non-taxable internal conversions.",
    },
    {
      providerTransactionType: "vault_withdrawal",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Vault withdrawals are internal ownership-preserving movements.",
    },
    {
      providerTransactionType: "wrap_asset",
      transactionTypeKey: "internal_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes: "Wrap/unwrap actions are modeled as non-taxable internal conversions.",
    },
    {
      providerTransactionType: "fcm_futures_usdc_sell",
      transactionTypeKey: "sell_fiat",
      inventoryEffect: "disposal",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "USDC liquidation into USD is represented as a disposal by default.",
    },
    {
      providerTransactionType: "fcm_futures_usdc_sell_additional_encumberment_rollup",
      transactionTypeKey: "sell_fiat",
      inventoryEffect: "disposal",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Additional encumberment rollups liquidate USDC into USD by default.",
    },
    {
      providerTransactionType: "staking_reward",
      transactionTypeKey: "staking_reward",
      inventoryEffect: "income",
      taxTreatment: "taxable_by_default",
      resolutionStrategy: "static",
      pairedRecordRequired: false,
      mappingStatus: "approved",
      sourceNotes: "Observed live Coinbase staking rewards are taxable income.",
    },
    {
      providerTransactionType: "retail_instant_unstaking",
      transactionTypeKey: "staking_withdrawal",
      inventoryEffect: "internal_transfer",
      taxTreatment: "requires_additional_rule_logic",
      resolutionStrategy: "amount_sign_fee",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes:
        "Instant unstaking is modeled as principal release on positive rows and a fee-like spread on negative rows.",
    },
    {
      providerTransactionType: "retail_eth2_deprecation",
      transactionTypeKey: "token_migration_transfer",
      inventoryEffect: "internal_transfer",
      taxTreatment: "non_taxable_by_default",
      resolutionStrategy: "no_leg",
      pairedRecordRequired: true,
      mappingStatus: "approved",
      sourceNotes: "ETH2 deprecation flows are modeled as non-taxable migration events.",
    },
  ]

export const coinbaseDefaultCurrencyMappings: ReadonlyArray<CoinbaseDefaultCurrencyMapping> = [
  {
    currencyCode: "BTC",
    mappingKind: "asset",
    canonicalAssetSymbol: "BTC",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "ETH",
    mappingKind: "asset",
    canonicalAssetSymbol: "ETH",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "ETH2",
    mappingKind: "asset",
    canonicalAssetSymbol: "ETH",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Coinbase-specific alias for staked / deprecated ETH balances.",
  },
  {
    currencyCode: "ADA",
    mappingKind: "asset",
    canonicalAssetSymbol: "ADA",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "DOT",
    mappingKind: "asset",
    canonicalAssetSymbol: "DOT",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "SOL",
    mappingKind: "asset",
    canonicalAssetSymbol: "SOL",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "ZEC",
    mappingKind: "asset",
    canonicalAssetSymbol: "ZEC",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "EURC",
    mappingKind: "asset",
    canonicalAssetSymbol: "EURC",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "TAO",
    mappingKind: "asset",
    canonicalAssetSymbol: "TAO",
    canonicalFiatCurrency: null,
    mappingStatus: "approved",
    sourceNotes: "Direct Coinbase currency mapping.",
  },
  {
    currencyCode: "EUR",
    mappingKind: "fiat",
    canonicalAssetSymbol: null,
    canonicalFiatCurrency: "EUR",
    mappingStatus: "approved",
    sourceNotes: "Fiat currency mapping used for native amounts and fiat-denominated fees.",
  },
]
